# Site settings
title: Advanced HTML/CSS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaylalewis.github.io/advancedhtmlcss" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
